#MongoDB deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0.5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd

---
#Mongdb Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP

---

#Deployment Rotten-Potatoes Python APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-rotten-potatoes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-rotten-potatoes
  template:
    metadata:
      labels:
        app: web-rotten-potatoes
    spec:
      containers:
      - name: web-rotten-potatoes
        image: davitelesfranca/rotten-potatoes:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: admin
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: web-rotten-potatoes
spec:
  selector:
    app: web-rotten-potatoes
  ports:
  - port: 8080
    targetPort: 5000
    nodePort: 30000
  type: NodePort